# Generated by Django 5.1.1 on 2025-02-26 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tickets.ticket'),
        ),
    ]
