# Generated by Django 5.1.1 on 2025-02-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticketlog_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlog',
            name='ticket_qr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
