# Generated by Django 5.1.1 on 2025-02-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketlog_ticket_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
