# Generated by Django 5.1.1 on 2025-02-27 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='note',
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_qr', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.CharField(choices=[('CHECKIN', 'Check-In'), ('UPDATE', 'Update'), ('OTHER', 'Other'), ('ERROR', 'Error'), ('SYSTEM', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tickets.ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='TicketLog',
        ),
    ]
