# Generated by Django 5.1.1 on 2025-03-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_note_log_delete_ticketlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='invited',
            field=models.BooleanField(default=False),
        ),
    ]
