# Generated by Django 5.1.6 on 2025-03-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_eventeesettings_ticket_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
