# Generated by Django 5.1.6 on 2025-03-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
