# Generated by Django 5.1.1 on 2025-05-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventeesettings',
            name='required_ticket_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
