# Generated by Django 5.1.1 on 2025-05-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_eventeesettings_required_ticket_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
