# Generated by Django 5.1.1 on 2025-01-01 00:00

from django.db import migrations
from django.core.management import call_command


def create_default_user(apps, schema_editor):
    """Create default TBM user."""
    # Only create user if no users exist
    User = apps.get_model('auth', 'User')
    if not User.objects.exists():
        call_command('create_default_user')


def reverse_create_default_user(apps, schema_editor):
    """Remove default TBM user."""
    User = apps.get_model('auth', 'User')
    try:
        user = User.objects.get(username='TBM')
        user.delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_company_name'),
    ]

    operations = [
        migrations.RunPython(create_default_user, reverse_create_default_user),
    ]