# Generated by Django 5.1.1 on 2025-05-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0012_create_default_user"),
        ("tickets", "0012_rename_eventeesettings_to_appsettings"),
    ]

    operations = []
