# Generated by Django 5.1.1 on 2025-05-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_log_event_type'),
        ('tickets', '0013_merge_20250528_2044'),
    ]

    operations = [
    ]
