# Generated by Django 5.1.9 on 2025-05-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_merge_20250530_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='auto_print_on_scan',
            field=models.BooleanField(default=True, verbose_name='Automatically print labels when scanning'),
        ),
        migrations.AlterField(
            model_name='log',
            name='event_type',
            field=models.CharField(choices=[('CHECKIN', 'Check-In'), ('UPDATE', 'Update'), ('CREATE', 'Create'), ('DELETE', 'Delete'), ('IMPORT', 'Import'), ('PRINT', 'Print'), ('BULK_PRINT', 'Bulk Print'), ('ERROR', 'Error'), ('SYSTEM', 'System'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
