# Generated by Django 5.2.12 on 2026-03-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_appsettings_auto_print_on_scan_alter_log_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='printer_1_name',
            field=models.CharField(default='TDP-2251', max_length=255, verbose_name='Printer 1 Name'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='printer_2_name',
            field=models.CharField(default='TDP-2252', max_length=255, verbose_name='Printer 2 Name'),
        ),
    ]
