# Generated by Django 5.2.12 on 2026-03-22 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_add_printer_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eventee_api_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Eventee API Token')),
                ('required_ticket_fields', models.JSONField(blank=True, default=list, verbose_name='Required Ticket Fields')),
                ('printer_1_name', models.CharField(default='TDP-2251', max_length=255, verbose_name='Printer 1 Name')),
                ('printer_2_name', models.CharField(default='TDP-2252', max_length=255, verbose_name='Printer 2 Name')),
                ('auto_print_on_scan', models.BooleanField(default=True, verbose_name='Automatically print labels when scanning')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event_name',
        ),
        migrations.AddField(
            model_name='log',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tickets.event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.event'),
        ),
    ]
