# Generated by Django 5.2.12 on 2026-03-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_default_event_for_existing_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='print_backend',
            field=models.CharField(choices=[('direct', 'Direct (this server)'), ('webusb', 'WebUSB (browser → USB)'), ('agent', 'Local Agent (browser → agent.exe)')], default='direct', max_length=20, verbose_name='Print Backend'),
        ),
    ]
