# Generated by Django 5.2.12 on 2026-03-26 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_agent_tokens(apps, schema_editor):
    Event = apps.get_model('tickets', 'Event')
    for event in Event.objects.filter(print_backend='agent', agent_token=''):
        event.agent_token = uuid.uuid4().hex
        event.save(update_fields=['agent_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_add_print_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='agent_token',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Agent Token'),
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_queue', models.CharField(default='1', max_length=2)),
                ('print_data', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printing', 'Printing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='tickets.event')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(backfill_agent_tokens, migrations.RunPython.noop),
    ]
