# Generated by Django 5.2.12 on 2026-05-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_event_agent_token_printjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='label_copies',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of label copies to print per badge (1 = single, 2 = double-sided, etc.)', verbose_name='Label Copies'),
        ),
    ]
