# Generated by Django 5.2.12 on 2026-09-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_event_label_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventee_send_email',
            field=models.BooleanField(default=False, verbose_name='Send Eventee invitation e-mails'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='eventee_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sync_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
