# Generated by Django 5.2.12 on 2026-09-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_event_eventee_send_email_ticket_eventee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventee_invite_default',
            field=models.BooleanField(default=True, verbose_name='Eventee sync checked by default on new tickets'),
        ),
    ]
